global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-datalake-informatica
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-datalake-informatica-medium:
    parameter_input: medium-cluster.json
    template_file: informatica-datalake-master.template
    regions:
      - eu-west-1
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
#  quickstart-datalake-informaticat2:
#    parameter_input: quickstart-datalake-informatica-example-params2.json
#    template_file: quickstart-datalake-informatica-example2.template
  quickstart-datalake-informatica-small:
    parameter_input: small-cluster.json
    template_file: informatica-datalake-master.template
      - ap-northeast-1
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1